site_name: Blender，我秒了

repo_url: https://github.com/mumu-lhl/Blender-I-Learn-It
repo_name: mumu-lhl/Blender-I-Learn-It
edit_uri: edit/main/docs/

theme:
  name: materialx
  features:
    - content.action.edit
    - content.action.view

    - search.suggest
    - search.share

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - git-revision-date-localized:
      enable_creation_date: true

  - git-committers:
      repository: mumu-lhl/Blender-I-Learn-It
      branch: main

  - search:
      lang: zh

  - optimize
